export enum TransactionStatus {
  EM_PROCESSAMENTO = 'EM_PROCESSAMENTO',
  DEVOLVIDO = 'DEVOLVIDO',
  NAO_REALIZADO = 'NAO_REALIZADO',
  ATIVA = 'ATIVA',
  CONCLUIDA = 'CONCLUIDA',
  REMOVIDA_PELO_USUARIO_RECEBEDOR = 'REMOVIDA_PELO_USUARIO_RECEBEDOR',
  REMOVIDA_PELO_PSP = 'REMOVIDA_PELO_PSP',
  REEMBOLSO = 'REEMBOLSO',
}